# No shadows
shadow = false;

# No fading
fading = false;

# Backend
backend = "xrender";

# VSync
vsync = true;

# Misc
detect-rounded-corners = true;
detect-client-opacity = true;
detect-transient = true;
use-damage = true;
frame-opacity = 0.9;
